### ISSUE TITLE
group condition doc unclear

### ISSUE THREAD

**Issue by pywebdesign** [oelmekki/activerecord_any_of#30]
Hi,

I really can't figure out from the doc how to group condition that are not expressable with the symbol hash notation. On the doc we have

````ruby
User.where.any_of({first_name: 'John', last_name: 'Joe'}, {first_name: 'Simon', last_name: 'Joe'})
````

I am trying to add an array expressable condition in a group like so:

````ruby
Conversation.where.any_of(
          [{receiver: user}, ["receiver_hide !=", not_hidden]],
          [{sender: user}, ["sender_hide !=", not_hidden]]
        )
````

the second condition is simply ignored so it act exactly like

````ruby
Conversation.where.any_of(
          {receiver: user},
          {sender: user}
        )
````

Is it possible to do? we could clarify this situation in the doc.

thank you

**Comment by oelmekki** [comment]
Hi @pywebdesign,

For the more complex queries, you can pass relations as parameters:

```ruby
received = Conversation.where( receiver: user ).where( "receiver_hide != ?", not_hidden )
sent = Conversation.where( sender: user ).where( "sender_hide != ?", not_hidden )
Conversation.where.any_of( received, sent )
```

**Comment by pywebdesign** [comment]
that is very nice, thank you!
