### ISSUE TITLE
Where unnecessary wrappers

### ISSUE THREAD

**Issue by mojidabckuu** [oelmekki/activerecord_any_of#37]
I am trying to use multiple conditions to perform search

That what I have in my code
```ruby
attributes = ['email', 'first_name', 'last_name', 'mobile', 'nickname']
conditions = attributes.map { |attribute| "lower(#{attribute}) LIKE %#{params[:q].downcase}%"}
User.where.any_of(*conditions)
```
But unfortunately `any_of` produces incorrect SQL
Here is how any_of produces SQL
```SQL
SELECT "users".* FROM "users" WHERE ((((((lower(email) LIKE '%test%') OR (lower(first_name) LIKE '%test%')) OR (lower(last_name) LIKE '%test%')) OR (lower(mobile) LIKE '%test%')) OR (lower(nickname) LIKE '%test%')));
```
You can see extra `()`
I ran `EXPLAINE ANALYSE` to see productivity
For wrong SQL:
```SQL
(actual time=0.037..0.392 
Planning time: 0.185 ms
Execution time: 0.475 ms
```
For correct SQL:
```SQL
actual time=0.013..0.406 
Planning time: 0.095 ms
Execution time: 0.463 ms
```
But I can't estimate is it critical or not? It shouldn't be like this, right?

**Comment by oelmekki** [comment]
Hi @mojidabckuu ,

Having good looking sql queries is not a priority for
`activerecord_any_of`. If you need this kind of aesthetic
precision, you should probably write your OR queries manually.

**Comment by mojidabckuu** [comment]
@oelmekki got it.
